### PR TITLE
(ja) Update japanese.json

### PR DESCRIPTION
**Pull request by fisuda**
I have updated the japanese.json. It would be great if you could review this PR.

### CODE REVIEW

**Comment by jason-fox** [comment]
Thanks. I see you recommend katakana over kanji for the technical attribute names.

I may look at merging this, or I may just apply your changes directly on `master` then close this PR without merge once I am done. I need to check that the JSON-LD `@context` remains valid.

What I'll do is finish the remaining tutorial texts first with my bad Japanese attributes and  update the responses once I've pushed your changes.

**Comment by fisuda** [comment]
> I see you recommend katakana over kanji for the technical attribute names.

It's basically right. But, for instance, 'attribute' is translated  to ’アトリービュート' or '属性'. It's a difficult issue. Please feel free to contact me if you have an issue to translate to Japanese.

**Comment by jason-fox** [comment]
Merged  by applying changes manually - closing

**Comment by fisuda** [comment]
Hi @jason-fox,

On this PR, I updated the following words as alter attributes.
```
    "type": "@type",
    "id": "@id",
```
You replaced them with the following words. But, these words are strange for Japanese.
```
    "類": "@type",
    "氏名": "@id",
```
If we can't use `type` and `id` as alter attributes, could you replace with the following words?
```
    "タイプ": "@type",
    "識別子": "@id",
```
https://ja.wikipedia.org/wiki/%E8%AD%98%E5%88%A5%E5%AD%90

Thanks!

**Comment by jason-fox** [comment]
Thanks for those additional translations / clarifications - I have applied them where necessary.

In the final example,  I am trying to demonstrate that any attributes including core context  can be  replaced if the need calls for it.

It is therefore important that the core terms `type` and `id` are replaced by something else - Japanese characters are great here because they look very different in the response to the usual simple `A-Z` ASCII chars - and of course it is equally important that they *make sense* to someone who can actually read them. 😄 

I'm not sure how much localization a real Japanese developer would actually do when really interacting with NGSI-LD - but the point is that anything can be replaced if necessary.

**Comment by fisuda** [comment]
Thank you for amending the japanese.json file!
I understand your thoughts for this tutorial.

**Pull request closed without merging**
